### ISSUE TITLE
build issue in cloud9

### ISSUE THREAD

**Issue by shanshanyang** [HyphnKnight/Teflon#1]
Test environment: cloud9.io, cloned github repo, and run in cloud9 instance

cloud9 IDE stack: https://en.wikipedia.org/wiki/Cloud9_IDE

Steps to reproduce: 
run `npm i`
run `npm node bin/build.js`

Warning / Error: 
- `[BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "100KB".`
- `Error : media.copy  has failed to parse /home/ubuntu/workspace/source
                      type : Error
                      message : ENOENT: no such file or directory, lstat '/home/ubuntu/workspace/source/media'`

**Comment by HyphnKnight** [comment]
This should be fixed as of the latest build, try again (:

**Comment by shanshanyang** [comment]
Error is fixed, however the babel note is still there.

edit babel.js with the code below fixed it: 
{ presets : ['es2015'], compact: false }

https://github.com/laravel/elixir/issues/153

**Comment by HyphnKnight** [comment]
Changed and fixed (: thanks
